mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'


urlpatterns = [
    path('', mainapp.main_view, name='main'),
    path('points/', mainapp.PointsListView.as_view(), name='points'),
    path('points/create/', mainapp.PointCreateView.as_view(), name='create_point'),
    path('points/<pk>/', mainapp.PointUpdateView.as_view(), name='update_point'),
    path('points/delete/<pk>/', mainapp.PointDeleteView.as_view(), name='delete_point'),
    path('intervals/', mainapp.IntervalsListView.as_view(), name='intervals'),
    path('intervals/create/', mainapp.IntervalCreateView.as_view(), name='create_interval'),
    path('intervals/<pk>/', mainapp.IntervalUpdateView.as_view(), name='update_interval'),
    path('intervals/delete/<pk>/', mainapp.IntervalDeleteView.as_view(), name='delete_interval'),
    path('comments/', mainapp.CommentsListView.as_view(), name='comments'),
    path('comments/create/', mainapp.CommentCreateView.as_view(), name='create_comment'),
    path('comments/<pk>/', mainapp.CommentUpdateView.as_view(), name='update_comment'),
    path('comments/delete/<pk>/', mainapp.CommentDeleteView.as_view(), name='delete_comment'),
]

test_points_intervals/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp')),

]

mainapp/models.py
from django.db import models


# Create your models here.


class Comment(models.Model):
    text = models.CharField(max_length=150, verbose_name='Комментарий')
    start_time = models.IntegerField(null=True, blank=True, verbose_name='C: ')
    finish_time = models.IntegerField(null=True, blank=True, verbose_name='До: ')


class Point(models.Model):
    time = models.IntegerField(verbose_name='Время')
    val = models.FloatField(verbose_name='Значение')
    comment = models.ForeignKey(Comment, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Комментарий')
    more_time = models.IntegerField(verbose_name='Верхний допуск по времени')
    less_time = models.IntegerField(verbose_name='Нижний допуск по времени')
    more_value = models.IntegerField(verbose_name='Верхний допуск по значению')
    less_value = models.IntegerField(verbose_name='Нижний допуск по значению')

    def __str__(self):
        return f'Time: {self.time} Value: {self.val}'


class Interval(models.Model):
    val = models.IntegerField(verbose_name='Интервал')
    point_a = models.ForeignKey(Point, on_delete=models.CASCADE, verbose_name='Начальная точка', related_name='point_a')
    point_b = models.ForeignKey(Point, on_delete=models.CASCADE, verbose_name='Конечная точка', related_name='point_b')
    comment = models.ForeignKey(Comment, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Комментарий')

mainapp/forms.py
from django import forms

from mainapp.models import Point, Interval, Comment


class PointUpdateForm(forms.ModelForm):

    class Meta:
        model = Point
        fields = '__all__'


class IntervalUpdateForm(forms.ModelForm):

    class Meta:
        model = Interval
        fields = '__all__'


class CommentUpdateForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = '__all__'

mainapp/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from mainapp.forms import PointUpdateForm, IntervalUpdateForm, CommentUpdateForm
from mainapp.models import Point, Interval, Comment


def main_view(request):
    return render(request, 'mainapp/index.html')


class PointsListView(ListView):
    model = Point
    queryset = Point.objects.order_by('pk')
    template_name = 'mainapp/points.html'
    context_object_name = 'points'
    paginate_by = 20


class PointCreateView(CreateView):
    model = Point
    template_name = 'mainapp/point_create.html'
    form_class = PointUpdateForm
    success_url = reverse_lazy('mainapp:points')


class PointUpdateView(UpdateView):
    model = Point
    form_class = PointUpdateForm
    template_name = 'mainapp/point_update.html'
    success_url = reverse_lazy('mainapp:points')


class PointDeleteView(DeleteView):
    model = Point
    template_name = 'mainapp/point_delete.html'
    success_url = reverse_lazy('mainapp:points')


class IntervalsListView(ListView):
    model = Interval
    queryset = Interval.objects.order_by('pk')
    template_name = 'mainapp/intervals.html'
    context_object_name = 'intervals'
    paginate_by = 20


class IntervalCreateView(CreateView):
    model = Interval
    template_name = 'mainapp/interval_create.html'
    form_class = IntervalUpdateForm
    success_url = reverse_lazy('mainapp:intervals')


class IntervalUpdateView(UpdateView):
    model = Interval
    form_class = IntervalUpdateForm
    template_name = 'mainapp/interval_update.html'
    success_url = reverse_lazy('mainapp:intervals')


class IntervalDeleteView(DeleteView):
    model = Interval
    template_name = 'mainapp/interval_delete.html'
    success_url = reverse_lazy('mainapp:intervals')


class CommentsListView(ListView):
    model = Comment
    queryset = Comment.objects.order_by('pk')
    template_name = 'mainapp/comments.html'
    context_object_name = 'comments'
    paginate_by = 20


class CommentCreateView(CreateView):
    model = Comment
    template_name = 'mainapp/comment_create.html'
    form_class = CommentUpdateForm
    success_url = reverse_lazy('mainapp:comments')


class CommentUpdateView(UpdateView):
    model = Comment
    form_class = CommentUpdateForm
    template_name = 'mainapp/comment_update.html'
    success_url = reverse_lazy('mainapp:comments')


class CommentDeleteView(DeleteView):
    model = Comment
    template_name = 'mainapp/comment_delete.html'
    success_url = reverse_lazy('mainapp:comments')

templates/mainapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

templates/mainapp/comment_create.html
{% extends 'mainapp/base.html' %}

{% block content %}

  <form class="form-horizontal col-6" method="post">
    {% csrf_token %}
    {{ form.as_p }}
  <button>Сохранить</button>
  </form>

{% endblock %}

templates/mainapp/comment_delete.html
{% extends 'mainapp/base.html' %}

{% block content %}

  <div class="user_delete text-center">
    Уверены, что хотите удалить точку с ID: {{ object.id }} ?
    <form action="{% url 'mainapp:delete_comment' pk=object.id %}" method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'mainapp:comments' %}">
        Отмена
      </a>
    </button>
  </div>

{% endblock %}

templates/mainapp/comment_update.html
{% extends 'mainapp/base.html' %}

{% block content %}

  <form class="form-horizontal col-6" method="post">
    {% csrf_token %}
    {{ form.as_p }}
  <button>Сохранить</button>
  </form>

{% endblock %}

templates/mainapp/comments.html
{% extends 'mainapp/base.html' %}

{% block content %}

  {% include 'mainapp/includes/inc_pages.html' %}
  <div class="d-flex flex-column align-items-center">
    {% for comment in comments %}
      <div class="d-flex">
        <div class="m-2">
          Comment ID: {{ comment.id }}
          Text: {{ comment.text }}
          From: {{ comment.start_time }}
          To: {{ comment.finish_time }}
        </div>
        <a class="m-2" href={% url 'mainapp:update_comment' pk=comment.id %}>Edit</a>
        <a class="m-2" href={% url 'mainapp:delete_comment' pk=comment.id %}>Delete</a>
      </div>
    {% endfor %}
    <a href={% url 'mainapp:create_comment' %}>Create Comment</a>
  </div>

{% endblock %}

templates/mainapp/includes/inc_pages.html
<a class="d-flex justify-content-center" href="{% url 'mainapp:main' %}">To Main</a>
<div class="d-flex justify-content-center col-md-12 text-center pages">
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span class="nav-link" aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="">
            <span class="nav-link " aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
      {% endif %}
      {#            {% for i in paginator.page_range %}#}
      {#                {% if page_obj.number == i %}#}
      {#                    <li class="page-item">#}
      {#                        <a class="page-link">#}
      {#                            <span class="nav-link pageActive">#}
      {#                                {{ i }}#}
      {#                            </span>#}
      {#                        </a>#}
      {#                    </li>#}
      {#                {% else %}#}
      {#                    <li class="page-item">#}
      {#                        <a class="page-link" href="?page={{ i }}">#}
      {#                            <span class="nav-link">#}
      {#                                {{ i }}#}
      {#                            </span>#}
      {#                        </a>#}
      {#                    </li>#}
      {#                {% endif %}#}
      {#            {% endfor %}#}
      <li class="page-item">
        <a class="page-link">
          <span class="nav-link pageActive">
              {{ page_obj.number }}
          </span>
        </a>
      </li>
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span class="nav-link" aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="">
            <span class="nav-link " aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
</div>

templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% block content %}
  <div class="d-flex justify-content-center">
    <a class="m-2" href="{% url 'mainapp:points' %}">Points</a>
    <a class="m-2" href="{% url 'mainapp:intervals' %}">Intervals</a>
    <a class="m-2" href="{% url 'mainapp:comments' %}">Comments</a>
  </div>
{% endblock %}

templates/mainapp/interval_create.html
{% extends 'mainapp/base.html' %}

{% block content %}

  <form class="form-horizontal col-6" method="post">
    {% csrf_token %}
    {{ form.as_p }}
  <button>Сохранить</button>
  </form>

{% endblock %}

templates/mainapp/interval_delete.html
{% extends 'mainapp/base.html' %}

{% block content %}

  <div class="user_delete text-center">
    Уверены, что хотите удалить точку с ID: {{ object.id }} ?
    <form action="{% url 'mainapp:delete_interval' pk=object.id %}" method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'mainapp:intervals' %}">
        Отмена
      </a>
    </button>
  </div>

{% endblock %}

templates/mainapp/interval_update.html
{% extends 'mainapp/base.html' %}

{% block content %}

  <form class="form-horizontal col-6" method="post">
    {% csrf_token %}
    {{ form.as_p }}
  <button>Сохранить</button>
  </form>

{% endblock %}

templates/mainapp/intervals.html
{% extends 'mainapp/base.html' %}

{% block content %}

  {% include 'mainapp/includes/inc_pages.html' %}
  <div class="d-flex flex-column align-items-center">
    {% for interval in intervals %}
      <div class="d-flex">
        <div class="m-2">
          Interval ID: {{ interval.id }}
          Value: {{ interval.val }}
          From: {{ interval.point_a.time }}
          To: {{ interval.point_b.time }}
        </div>
        <a class="m-2" href={% url 'mainapp:update_interval' pk=interval.id %}>Edit</a>
        <a class="m-2" href={% url 'mainapp:delete_interval' pk=interval.id %}>Delete</a>
      </div>
    {% endfor %}
    <a href={% url 'mainapp:create_interval' %}>Create Interval</a>
  </div>

{% endblock %}

templates/mainapp/point_create.html
{% extends 'mainapp/base.html' %}

{% block content %}

  <form class="form-horizontal col-6" method="post">
    {% csrf_token %}
    {{ form.as_p }}
  <button>Сохранить</button>
  </form>

{% endblock %}

templates/mainapp/point_delete.html
{% extends 'mainapp/base.html' %}

{% block content %}

  <div class="user_delete text-center">
    Уверены, что хотите удалить точку с ID: {{ object.id }} ?
    <form action="{% url 'mainapp:delete_point' pk=object.id %}" method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'mainapp:points' %}">
        Отмена
      </a>
    </button>
  </div>

{% endblock %}

templates/mainapp/point_update.html
{% extends 'mainapp/base.html' %}

{% block content %}

  <form class="form-horizontal col-6" method="post">
    {% csrf_token %}
    {{ form.as_p }}
  <button>Сохранить</button>
  </form>

{% endblock %}

templates/mainapp/points.html
{% extends 'mainapp/base.html' %}

{% block content %}

  {% include 'mainapp/includes/inc_pages.html' %}
  <div class="d-flex flex-column align-items-center">
    {% for point in points %}
      <div class="d-flex">
        <div class="m-2">Point ID: {{ point.id }} Time: {{ point.time }} Value: {{ point.val }}</div>
        <a class="m-2" href={% url 'mainapp:update_point' pk=point.id %}>Edit</a>
        <a class="m-2" href={% url 'mainapp:delete_point' pk=point.id %}>Delete</a>
      </div>
    {% endfor %}
    <a href={% url 'mainapp:create_point' %}>Create Point</a>
  </div>

{% endblock %}